# This file is used to set up a WordPress instance that uses Bitnami images
#
# It expects WP_HOME and WORDPRESS_DATABASE_PASSWORD env variables to be set
version: "3.9"

services:

  # https://hub.docker.com/r/bitnami/wordpress-nginx/
  # https://github.com/bitnami/containers/tree/main/bitnami/wordpress-nginx#readme
  # wp-content files are owned by 1001:root
  wordpress:
    image: bitnami/wordpress-nginx:6.0.2
    hostname: wordpress
    restart: always
    ports:
      - ${WORDPRESS_HTTP_PORT:-8888}:8080

    mem_limit: 92M
    cpus: "0.25"
    environment:
      WORDPRESS_BLOG_NAME: 'My test Bitnami WordPress'
      WORDPRESS_DATABASE_NAME: wp_db
      WORDPRESS_DATABASE_USER: wp_user
      WORDPRESS_DATABASE_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD:-p4ssw0rd}
      WORDPRESS_DEBUG: 'true'  # https://wordpress.org/support/article/debugging-in-wordpress/

      # set up the wp-config.php
      WORDPRESS_SITE_URL: ${WORDPRESS_SITE_URL:-http://localhost:8888}

      # make sure Jetpack uses our custom HTTP PORT
      WORDPRESS_EXTRA_WP_CONFIG_CONTENT: "define( 'JETPACK_SIGNATURE__HTTP_PORT', 8080 );"

    volumes:
      # run the setup script after WordPress container is set up
      # @see https://github.com/bitnami/containers/blob/main/bitnami/wordpress-nginx/6/debian-11/rootfs/post-init.sh
      - "./wordpress-setup.sh:/docker-entrypoint-init.d/wordpress-setup.sh:ro"

      # data persistency and sharing with SSH container
      - "wordpress_data:/bitnami/wordpress"
      - "opt_bitnami_data:/opt/bitnami/wordpress"

    # https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/
    labels:
      traefik.enable: true
      traefik.http.routers.wordpress.tls.certresolver: letsencrypt
      traefik.http.routers.wordpress.rule: Host(`${WORDPRESS_HOSTNAME:-wptest.dev.local}`)
      # https://doc.traefik.io/traefik/routing/services/#servers
      traefik.http.services.wordpress.loadbalancer.server.port: "8080"
      # https://doc.traefik.io/traefik/routing/services/#health-check
      traefik.http.services.wordpress.loadbalancer.healthCheck.path: "/wp-json"
      traefik.http.services.wordpress.loadbalancer.healthCheck.method: "HEAD"
      traefik.http.services.wordpress.loadbalancer.healthCheck.scheme: "http"
      traefik.http.services.wordpress.loadbalancer.healthCheck.interval: "10s"

    healthcheck:
      test: 'pgrep nginx'
      interval: 10s
      timeout: 1s
      retries: 5

  # https://github.com/bitnami/bitnami-docker-mariadb
  db-dev:
    image: docker.io/bitnami/mariadb:10.6
    hostname: mariadb
    restart: always
    mem_limit: 128M
    cpus: "0.1"
    environment:
      MARIADB_DATABASE: wp_db
      MARIADB_USER: wp_user
      MARIADB_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD:-p4ssw0rd}
      MARIADB_ROOT_PASSWORD: r00t
      MARIADB_SKIP_TEST_DB: 'yes'
    volumes:
      - mariadb:/bitnami/mariadb
    healthcheck:
      # use $$ to escape env variables
      test: 'mysql --user=$$MARIADB_USER --password=$$MARIADB_PASSWORD $$MARIADB_DATABASE -e "SHOW TABLES"'
      interval: 30s
      timeout: 5s
      retries: 10

  # https://docs.linuxserver.io/images/docker-openssh-server
  # https://github.com/linuxserver/docker-openssh-server/pkgs/container/openssh-server
  ssh-dev:
    image: ghcr.io/linuxserver/openssh-server:8.8_p1-r1-ls91
    hostname: openssh-server
    restart: always
    ports:
      - '62222:2222'

    mem_limit: 32M
    cpus: "0.01"

    environment:
      PASSWORD_ACCESS: 'true'
      USER_NAME: wordpress
      USER_PASSWORD: ${SSH_PASSWORD:-p4ssw0rd}
      PUBLIC_KEY_FILE: /config/.ssh_key.pub  # see "volumes" below
      # ensure permissions to the file match those from the wordpress image
      # https://docs.linuxserver.io/images/docker-openssh-server#user-group-identifiers
      PUID: "1001"
      GUID: "0"

      # expose these variables so that the shell will see them (see open-ssh-setup-env-vars.sh script below)
      # wp-load.php is required in the SSH container and it needs to connect to the database
      WORDPRESS_DATABASE_NAME: wp_db
      WORDPRESS_DATABASE_USER: wp_user
      WORDPRESS_DATABASE_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD:-p4ssw0rd}

    volumes:
      # see the README.md file on how to regenerate the keys pair
      - "./ssh_key.pub:/config/.ssh_key.pub"

      # allow modifying WordPress files via SSH
      - "wordpress_data:/bitnami/wordpress"
      - "opt_bitnami_data:/opt/bitnami/wordpress"

      # Install php-cli inside the ssh container
      # https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
      - ./open-ssh-setup.sh:/custom-cont-init.d/open-ssh-setup.sh:ro

      # wp-cli YAML config file
      # https://make.wordpress.org/cli/handbook/references/config/#config-files
      - ./wp-cli-config.yml:/home/wordpress/.wp-cli/config.yml:ro
      - ./wp-cli-config.yml:/root/.wp-cli/config.yml:ro

volumes:

  mariadb:
  opt_bitnami_data:
  wordpress_data:

# make the wordpress container discoverable by traefik
# https://docs.docker.com/compose/networking/#configure-the-default-network
#
# docker network create public-network
networks:
  default:
    name: public-network
    external: true
